export type SeoLandingPage = {
  slug: string;
  title: string;
  intent: string;
  category: "core-local" | "concern" | "luxury" | "education" | "authority";
  problem: string;
  solution: string[];
};

export const seoPages: SeoLandingPage[] = [
  { slug: "facial-brandon-fl", title: "Facial Brandon FL", intent: "local facial booking", category: "core-local", problem: "You want a trusted facial specialist in Brandon with clinical results and a calm experience.", solution: ["Custom facials for all skin types", "Acne, glow, and anti-aging options", "Personalized skin analysis and treatment mapping"] },
  { slug: "facial-tampa-fl", title: "Facial Tampa FL", intent: "facial near Tampa", category: "core-local", problem: "You need a luxury-clinical facial option close to Tampa that feels personalized.", solution: ["Clinical-luxury facials near Tampa", "Skin correction plus glow enhancement"] },
  { slug: "luxury-facial-brandon-fl", title: "Luxury Facial Brandon FL", intent: "premium facial booking", category: "core-local", problem: "You want elevated skincare without sacrificing clinical clarity.", solution: ["High-end skincare experience", "Barrier repair and hydration therapy"] },
  { slug: "acne-facial-brandon-fl", title: "Acne Facial Brandon FL", intent: "acne support in Brandon", category: "core-local", problem: "Breakouts and inflammation keep returning without a structured plan.", solution: ["Breakout correction treatment", "Inflammation and congestion focus"] },
  { slug: "acne-treatment-tampa-fl", title: "Acne Treatment Tampa FL", intent: "acne treatment near Tampa", category: "core-local", problem: "You need a long-term acne strategy rather than one-off facials.", solution: ["Long-term acne correction system", "Personalized skin mapping"] },
  { slug: "dermaplaning-brandon-fl", title: "Dermaplaning Brandon FL", intent: "dermaplaning booking", category: "core-local", problem: "Texture, dullness, and buildup are reducing your skin glow.", solution: ["Instant glow and smooth texture", "Peach fuzz removal treatment"] },
  { slug: "dermaplaning-tampa-fl", title: "Dermaplaning Tampa FL", intent: "dermaplaning near Tampa", category: "core-local", problem: "You want visible brightening from gentle exfoliation.", solution: ["Exfoliation and skin brightening", "Glow-focused treatment support"] },
  { slug: "sensitive-skin-facial-brandon-fl", title: "Sensitive Skin Facial Brandon FL", intent: "sensitive skin treatment", category: "core-local", problem: "Your skin gets reactive with many treatments and needs safe care.", solution: ["Barrier-safe treatments", "Redness reduction protocol"] },
  { slug: "skin-care-specialist-brandon-fl", title: "Skin Care Specialist Brandon FL", intent: "find specialist", category: "core-local", problem: "You need expert guidance, not generic recommendations.", solution: ["Expert consultation and treatment planning", "Clinical and educational approach"] },
  { slug: "best-esthetician-brandon-fl", title: "Best Esthetician Brandon FL", intent: "top local provider", category: "core-local", problem: "You are comparing local providers and looking for trust signals.", solution: ["Authority positioning with clear methodology", "Reviews and transformation proof"] },
  { slug: "acne-treatment-for-adults", title: "Acne Treatment for Adults", intent: "adult acne help", category: "concern", problem: "Adult acne needs personalized and sustainable correction.", solution: ["Hormonal acne support", "Long-term correction plans"] },
  { slug: "cystic-acne-treatment-facial", title: "Cystic Acne Treatment Facial", intent: "cystic acne facial", category: "concern", problem: "Deep, painful breakouts need calming plus corrective care.", solution: ["Inflammation-targeting protocols", "Extraction and calming sequence"] },
  { slug: "hormonal-acne-facial-treatment", title: "Hormonal Acne Facial Treatment", intent: "hormonal acne strategy", category: "concern", problem: "Breakouts around your cycle need a treatment rhythm.", solution: ["Cycle-based breakout management", "Barrier-first correction"] },
  { slug: "blackhead-removal-facial", title: "Blackhead Removal Facial", intent: "blackhead treatment", category: "concern", problem: "Persistent blackheads and pores feel impossible to clear.", solution: ["Pore cleansing system", "Targeted congestion treatment"] },
  { slug: "congested-skin-treatment", title: "Congested Skin Treatment", intent: "congested skin help", category: "concern", problem: "Congested skin needs detoxification without over-stripping.", solution: ["Detox and exfoliation strategy", "Balanced recovery support"] },
  { slug: "sensitive-redness-facial", title: "Sensitive Redness Facial", intent: "redness reduction", category: "concern", problem: "Red, reactive skin needs gentle but effective protocols.", solution: ["Barrier restoration focus", "Calming treatment pathway"] },
  { slug: "rosacea-friendly-facial", title: "Rosacea Friendly Facial", intent: "rosacea-safe facial", category: "concern", problem: "Rosacea-prone skin requires careful, non-aggressive care.", solution: ["Ultra-gentle skin protocol", "Inflammation-aware treatment steps"] },
  { slug: "dry-skin-hydration-facial", title: "Dry Skin Hydration Facial", intent: "hydration facial", category: "concern", problem: "Chronic dryness and tightness reduce comfort and glow.", solution: ["Deep moisture infusion", "Hydration retention support"] },
  { slug: "oily-skin-facial-treatment", title: "Oily Skin Facial Treatment", intent: "oil control facial", category: "concern", problem: "Excess oil and enlarged pores need balancing not harsh stripping.", solution: ["Oil balance and pore refinement", "Customized maintenance plan"] },
  { slug: "uneven-skin-tone-treatment", title: "Uneven Skin Tone Treatment", intent: "tone correction", category: "concern", problem: "Uneven tone and dullness need strategic brightening.", solution: ["Pigmentation and brightening system", "Targeted corrective protocol"] },
  { slug: "hyperpigmentation-facial", title: "Hyperpigmentation Facial", intent: "dark spot correction", category: "concern", problem: "Dark spots persist without consistent treatment and routine planning.", solution: ["Dark spot correction", "Barrier-safe brightening support"] },
  { slug: "melasma-skin-treatment-facial", title: "Melasma Skin Treatment Facial", intent: "melasma management", category: "concern", problem: "Melasma needs long-term pigment management with gentle progression.", solution: ["Pigment management protocol", "Maintenance education path"] },
  { slug: "aging-skin-facial-treatment", title: "Aging Skin Facial Treatment", intent: "anti-aging support", category: "concern", problem: "Aging skin concerns need hydration, collagen support, and consistency.", solution: ["Collagen support and lifting", "Long-term rejuvenation planning"] },
  { slug: "fine-lines-facial-treatment", title: "Fine Lines Facial Treatment", intent: "fine line smoothing", category: "concern", problem: "Fine lines improve with routine treatment and barrier health.", solution: ["Hydration and smoothing system", "Texture and firmness strategy"] },
  { slug: "dull-skin-glow-facial", title: "Dull Skin Glow Facial", intent: "glow restoration", category: "concern", problem: "Dull skin needs cellular renewal plus hydration balance.", solution: ["Radiance restoration treatment", "Glow maintenance planning"] },
  { slug: "luxury-facial-experience-tampa", title: "Luxury Facial Experience Tampa", intent: "luxury experience", category: "luxury", problem: "You want an elevated ritual with measurable skin outcomes.", solution: ["Spa and clinical hybrid experience", "Personalized luxury protocols"] },
  { slug: "relaxing-facial-brandon-fl", title: "Relaxing Facial Brandon FL", intent: "relaxation facial", category: "luxury", problem: "Stress and skin inflammation often show up together.", solution: ["Calming skin plus nervous system reset", "Supportive restorative facials"] },
  { slug: "self-care-facial-experience", title: "Self Care Facial Experience", intent: "self-care treatment", category: "luxury", problem: "You want emotional and skin recovery at the same time.", solution: ["Emotional and skin wellness focus", "High-touch treatment flow"] },
  { slug: "spa-facial-vs-clinical-facial", title: "Spa Facial vs Clinical Facial", intent: "compare treatment types", category: "luxury", problem: "It is hard to choose between relaxation and corrective outcomes.", solution: ["Educational comparison", "Best-fit recommendation guidance"] },
  { slug: "what-is-a-custom-facial", title: "What is a Custom Facial", intent: "custom facial explainer", category: "luxury", problem: "Generic facials often miss your specific skin pattern.", solution: ["Explainer plus conversion page", "Personalized treatment framework"] },
  { slug: "best-facial-for-glow-skin", title: "Best Facial for Glow Skin", intent: "glow facial search", category: "luxury", problem: "You want immediate glow and sustainable skin quality.", solution: ["Glow optimization targeting", "Routine plus treatment pairing"] },
  { slug: "anti-aging-facial-treatment-tampa", title: "Anti Aging Facial Treatment Tampa", intent: "anti-aging Tampa", category: "luxury", problem: "You need anti-aging care that feels clinical but not harsh.", solution: ["Collagen stimulation system", "Hydration and firming support"] },
  { slug: "youthful-skin-facial-treatment", title: "Youthful Skin Facial Treatment", intent: "preventative care", category: "luxury", problem: "Preventative skincare works best with guided consistency.", solution: ["Preventative skincare education", "Maintenance treatment cadence"] },
  { slug: "skin-detox-facial-treatment", title: "Skin Detox Facial Treatment", intent: "skin reset", category: "luxury", problem: "Your skin feels overloaded and needs a guided reset.", solution: ["Purification and reset protocol", "Recovery-focused aftercare"] },
  { slug: "seasonal-facial-treatments", title: "Seasonal Facial Treatments", intent: "seasonal skincare", category: "luxury", problem: "Skin needs change season to season and routines should adapt.", solution: ["Seasonal skincare adjustments", "Season-specific treatment strategy"] },
  { slug: "how-to-fix-acne-naturally-professional-guide", title: "How to Fix Acne Naturally (Professional Guide)", intent: "educational acne query", category: "education", problem: "Natural acne advice online is often confusing or conflicting.", solution: ["Myth correction with professional guidance", "Evidence-based treatment options"] },
  { slug: "why-do-i-keep-breaking-out", title: "Why Do I Keep Breaking Out", intent: "breakout root cause", category: "education", problem: "Recurring breakouts need root-cause pattern recognition.", solution: ["Root cause education", "Corrective planning framework"] },
  { slug: "what-causes-hormonal-acne", title: "What Causes Hormonal Acne", intent: "hormonal acne education", category: "education", problem: "Hormonal acne patterns need cycle-aware treatment and routine support.", solution: ["Science-backed explanation", "Cycle-based correction guidance"] },
  { slug: "how-to-fix-skin-barrier-damage", title: "How to Fix Skin Barrier Damage", intent: "barrier repair education", category: "education", problem: "Compromised barrier skin needs repair before aggressive correction.", solution: ["Recovery protocol education", "Gentle rebuild strategy"] },
  { slug: "signs-of-damaged-skin-barrier", title: "Signs of Damaged Skin Barrier", intent: "barrier diagnostics", category: "education", problem: "Many clients are unsure whether their barrier is disrupted.", solution: ["Diagnostic guide", "Repair-first care plan"] },
  { slug: "how-often-should-you-get-a-facial", title: "How Often Should You Get a Facial", intent: "facial frequency", category: "education", problem: "Inconsistent schedules reduce treatment outcomes.", solution: ["Maintenance education", "Cadence by skin goal"] },
  { slug: "dermaplaning-benefits-explained", title: "Dermaplaning Benefits Explained", intent: "dermaplaning education", category: "education", problem: "Clients often need clarity on dermaplaning benefits and suitability.", solution: ["Exfoliation science page", "Suitability and outcome guidance"] },
  { slug: "best-skincare-routine-for-acne", title: "Best Skincare Routine for Acne", intent: "acne routine", category: "education", problem: "Acne routines fail when product order and tolerance are unclear.", solution: ["Structured routine guide", "Professional layering recommendations"] },
  { slug: "morning-vs-night-skincare-routine", title: "Morning vs Night Skincare Routine", intent: "routine comparison", category: "education", problem: "Morning and night goals differ and require different product roles.", solution: ["Educational routine breakdown", "AM vs PM optimization"] },
  { slug: "ingredients-that-cause-breakouts", title: "Ingredients That Cause Breakouts", intent: "comedogenic ingredient query", category: "education", problem: "Hidden triggers in product formulas can perpetuate acne.", solution: ["Ingredient awareness guide", "Trigger-identification support"] },
  { slug: "about-skin-by-emely-brandon-fl", title: "About Skin by Emely Brandon FL", intent: "brand trust", category: "authority", problem: "Prospective clients want to understand the studio mission and standards.", solution: ["Founder story and mission", "Clinical-luxury positioning"] },
  { slug: "meet-emely-matias-esthetician", title: "Meet Emely Matias Esthetician", intent: "founder credibility", category: "authority", problem: "High-trust bookings depend on founder credibility and fit.", solution: ["Personal branding page", "Experience and treatment philosophy"] },
  { slug: "why-choose-skin-by-emely", title: "Why Choose Skin by Emely", intent: "comparison decision", category: "authority", problem: "Clients compare options and need clear differentiators.", solution: ["Differentiation and trust positioning", "Outcome-focused methodology"] },
  { slug: "client-results-before-after-gallery", title: "Client Results Before After Gallery", intent: "proof search", category: "authority", problem: "Conversion often depends on visual proof and client outcomes.", solution: ["Transformation proof hub", "Pathway examples by concern"] },
  { slug: "skin-consultation-booking-page", title: "Skin Consultation Booking Page", intent: "book consultation", category: "authority", problem: "Users need a clear final step without friction or confusion.", solution: ["Conversion-focused booking page", "Consult-first treatment routing"] }
];

export function getSeoPage(slug: string) {
  return seoPages.find((p) => p.slug === slug);
}
